### ISSUE TITLE
Favourite-Papers-Task: lab members add your favourite paper to the blog post!

### ISSUE THREAD

**Issue by FlicAnderson** [ewallace/ewallace.github.io#53]
As part of the lab's git workshop today (27th Nov 2020), it'll be great if people can add their favourite paper with a link and a summary to the [favourite papers in the lab blog post](https://ewallace.github.io/blog/favourite-papers) via git!

Good luck folks!

**Comment by FlicAnderson** [comment]
This is for: @marahjn, @eszter-d, @RoseyBayne, @elizhughes, @3mma-mack, @swinterbourne and @DimmestP

**Comment by FlicAnderson** [comment]
@ewallace has already contributed, thanks! :+1:

**Comment by FlicAnderson** [comment]
And also for: @RachaelMurray

**Comment by ewallace** [comment]
Hi All, it would be amazing to finish off this blogpost with contributions from more members of the lab, soon.

Looking good so far with papers posted by @FlicAnderson , @marahjn , @eszter-d.

**Comment by ewallace** [comment]
I'm going to close this as a stale issue, even though it was never really finished.

Thanks @FlicAnderson for running a great workshop.
